name: sample_framework
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.1
  logging: ^1.0.2
  dio: ^4.0.6
  shared_preferences: ^2.0.13
  flutter_easyloading: ^3.0.3
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  connectivity_plus: ^2.3.0
  package_info_plus: ^1.4.2
  google_fonts: ^2.3.1
  url_launcher: ^6.0.20
  pretty_json: ^2.0.0
  cached_network_image: ^3.2.0
  app_settings: ^4.1.6
  rename: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

